<a href="https://colab.research.google.com/github/Gakmlr7896/pytorch-project/blob/main/deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

##Scalar - The scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#We can check the dimension of a tensor by using ndim attribute.
scalar.ndim

0

In [4]:
#To retrieve the number from the tensor and turn it from torch.tensor to a python integer we can use .item()!
scalar.item()

7

##Vectors - a vector is a single dimension tensor that can contain many numbers.
####As you can have a vector [1, 2] to describe 2 things you can have a vector [1, 2, 3] to describe 3 things as well!

In [5]:
#Vector
vector = torch.tensor([3, 4])
vector

tensor([3, 4])

In [6]:
#Check the dimension number of the vector.
vector.ndim

1

In [7]:
#Another important concept for tensors is their shape attribute - The shape tells you how the elements inside them are arranged.
vector.shape

torch.Size([2])

##Matrices - a metrix is a kinda more like a group of 2 or more vectors, it's also so flexable as same as vectors!

In [8]:
#Matrix
Matrix = torch.tensor([[4, 5],
                       [2, 9],
                       [3, 1]])
Matrix

tensor([[4, 5],
        [2, 9],
        [3, 1]])

In [9]:
#Matrices are a 2 dimdension tensors!
Matrix.ndim

2

In [10]:
#The shape of the matrix will be 3, 2 because 3 elements deep and 2 elements wide.
Matrix.shape

torch.Size([3, 2])

##Tensors - A tensor can contain more numbers & it's so flexable as well!

In [12]:
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 4 ,6],
                        [2, 5, 8]]])
Tensor

tensor([[[1, 2, 3],
         [3, 4, 6],
         [2, 5, 8]]])

In [13]:
Tensor.ndim

3

In [14]:
Tensor.shape

torch.Size([1, 3, 3])

##Creating a ranadom tesnor.

In [42]:
#We can creat random tesnor by using torch.rand
random_tensor = torch.rand(size=(255, 255, 5))
random_tensor, random_tensor.dtype, random_tensor.shape
#.dtype shows as the data type of a tensor.

(tensor([[[0.3668, 0.3848, 0.6309, 0.3753, 0.1271],
          [0.6564, 0.4131, 0.9713, 0.1273, 0.2133],
          [0.4410, 0.0452, 0.1837, 0.9234, 0.3498],
          ...,
          [0.8419, 0.0607, 0.4274, 0.3299, 0.5311],
          [0.2826, 0.3533, 0.9703, 0.1015, 0.6671],
          [0.3879, 0.3559, 0.8601, 0.4223, 0.4616]],
 
         [[0.1013, 0.4742, 0.5622, 0.1870, 0.3294],
          [0.1953, 0.4062, 0.0211, 0.1216, 0.6086],
          [0.8508, 0.0474, 0.8986, 0.1694, 0.5502],
          ...,
          [0.0580, 0.0975, 0.2521, 0.0907, 0.3289],
          [0.2633, 0.4190, 0.4441, 0.3836, 0.0644],
          [0.8327, 0.4347, 0.6314, 0.0230, 0.4045]],
 
         [[0.2169, 0.8973, 0.1497, 0.9153, 0.2380],
          [0.4436, 0.6181, 0.6638, 0.3413, 0.5277],
          [0.2846, 0.1461, 0.8558, 0.6824, 0.0280],
          ...,
          [0.7295, 0.0256, 0.4631, 0.7829, 0.2045],
          [0.3588, 0.5551, 0.7767, 0.3486, 0.9478],
          [0.4718, 0.2072, 0.0904, 0.4930, 0.6360]],
 
         .

In [44]:
#You can make a random tensor of all zeros.
zeros = torch.zeros(size=(5, 5, 5))
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [46]:
#You can make a tensor of all ones.
ones = torch.ones(size=(5, 5, 5))
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

##Sometimes you might need or want a range of the numbers such as 1 to 10, 10 to 100.

In [50]:
#We are gonna use torch.arange(start, end, step)
#start = start of range (e.g. 0)
#end = end of range (e.g. 10)
#step = how many steps in between each value (e.g. 1)
range = torch.arange(0, 10, 1)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
#Sometimes you might want a tensor with the same dtype and the same shape but with a different numbers.
same_zeros = torch.zeros_like(input=range)
same_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])